// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUN6DnoyFj-wu1x3Ro3OwcUPz4NeTUyvo',
    appId: '1:285268153857:android:372660e87ccbb9cf23d200',
    messagingSenderId: '285268153857',
    projectId: 'nike-shop-2',
    storageBucket: 'nike-shop-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHR-IlqXp4k9cHlzeJr1cGB3pm_J6TPIs',
    appId: '1:285268153857:ios:e545938fb275b4e323d200',
    messagingSenderId: '285268153857',
    projectId: 'nike-shop-2',
    storageBucket: 'nike-shop-2.appspot.com',
    androidClientId: '285268153857-o5cd01rdq3v6vt9j0gdu54l2vmucihi8.apps.googleusercontent.com',
    iosClientId: '285268153857-ruq1n16j3f88hqdb0c0o4oosueuc4kut.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}